In [88]:
import pandas as pd
df = pd.read_csv("./elon_musk.csv", encoding="latin1")
df.head()

                                                Text
0            https://en.wikipedia.org/wiki/Elon_Musk
1  Elon Reeve Musk FRS (/?i?l?n/ EE-lon; born Jun...
2  Musk was born to a Canadian mother and White S...
3  In 2002, Musk founded SpaceX, an aerospace man...
4  Musk has been criticized for making unscientif...

### 1. Removing URLs 
 
**Instruction**: URLs should be removed because they do not provide word-level information  
for text analysis.

In [89]:
df['Text'] = df['Text'].str.replace(r'http\S+|www\. \s+', '', regex=True)
df

                                                Text
0
1  Elon Reeve Musk FRS (/?i?l?n/ EE-lon; born Jun...
2  Musk was born to a Canadian mother and White S...
3  In 2002, Musk founded SpaceX, an aerospace man...
4  Musk has been criticized for making unscientif...

### 2. Removing Punctuation  
 
**Instruction**: Remove punctuation to reduce complexity, as it typically does not hold vital  
information.

In [90]:
df['Text'] = df['Text'].str.translate(str.maketrans('', '', string.punctuation))
df

                                                Text
0
1  Elon Reeve Musk FRS iln EElon born June 28 197...
2  Musk was born to a Canadian mother and White S...
3  In 2002 Musk founded SpaceX an aerospace manuf...
4  Musk has been criticized for making unscientif...

### 3. Removing Stop Words 
 
**Instruction**: Remove stopwords (common words like articles and prepositions) because they  
add little to no value to the meaning of the sentence.

In [91]:
common_stopwords = pd.read_csv("./common_stopwords.txt")
stop_words = list(common_stopwords['STOP_WORDS'])
pattern = r'\b(' + '|'.join(stop_words) + r')\b'
df['Text'] = df['Text'].str.replace(pattern, '', regex=True)
df

                                                Text
0
1  Elon Reeve Musk FRS iln EElon born June 28 197...
2  Musk  born   Canadian mother  White South Afri...
3  In 2002 Musk founded SpaceX  aerospace manufac...
4  Musk   criticized  making unscientific  contro...

In [92]:
pattern

"\\b(a|about|above|after|again|against|all|am|an|and|any|are|aren't|as|at|be|because|been|before|being|below|between|both|but|by|can't|cannot|could|couldn't|did|didn't|do|does|doesn't|doing|don't|down|during|each|few|for|from|further|had|hadn't|has|hasn't|have|haven't|having|he|he'd|he'll|he's|her|here|here's|hers|herself|him|himself|his|how|how's|i|i'd|i'll|i'm|i've|if|in|into|is|isn't|it|it's|its|itself|let's|me|more|most|mustn't|my|myself|no|nor|not|of|off|on|once|only|or|other|ought|our|ours\tourselves|out|over|own|same|shan't|she|she'd|she'll|she's|should|shouldn't|so|some|such|than|that|that's|the|their|theirs|them|themselves|then|there|there's|these|they|they'd|they'll|they're|they've|this|those|through|to|too|under|until|up|very|was|wasn't|we|we'd|we'll|we're|we've|were|weren't|what|what's|when|when's|where|where's|which|while|who|who's|whom|why|why's|with|won't|would|wouldn't|you|you'd|you'll|you're|you've|your|yours|yourself|yourselves)\\b"

### 4. Lowercasing 
 
**Instruction**: Lowercase your text to improve general accuracy, as many language models  
treat capital letters differently. It is generally recommended for an English corpus.

In [93]:
df['Text'] = df['Text'].str.lower()
df

                                                Text
0
1  elon reeve musk frs iln eelon born june 28 197...
2  musk  born   canadian mother  white south afri...
3  in 2002 musk founded spacex  aerospace manufac...
4  musk   criticized  making unscientific  contro...

### 5. Tokenization 
 
**Instruction**: This is the foundational step in IR-the process of breaking your text (corpus)  
into individual units called tokens (by Sentence, by Paragraph, or by word).

In [94]:
from nltk.tokenize import sent_tokenize, word_tokenize

df['word_tokens'] = df['Text'].apply(word_tokenize)
df['sentence_tokens'] = df['Text'].apply(sent_tokenize)

### 6. Stemming (Reduction to Root Word) 
 
**Instruction**: Use stemming to reduce inflected words to their word stem. 
Method: It is a heuristic process that cuts off the ends of words.

In [95]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")

df['word_stemming'] = df['Text'].apply(lambda x: [stemmer.stem(word) for word in word_tokenize(x)])
df

,Text,word_tokens,sentence_tokens,word_stemming
0,,[],[],[]
1,elon reeve musk frs iln eelon born june 28 197...,"[elon, reeve, musk, frs, iln, eelon, born, jun...",[elon reeve musk frs iln eelon born june 28 19...,"[elon, reev, musk, frs, iln, eelon, born, june..."
2,musk born canadian mother white south afri...,"[musk, born, canadian, mother, white, south, a...",[musk born canadian mother white south afr...,"[musk, born, canadian, mother, white, south, a..."
3,in 2002 musk founded spacex aerospace manufac...,"[in, 2002, musk, founded, spacex, aerospace, m...",[in 2002 musk founded spacex aerospace manufa...,"[in, 2002, musk, found, spacex, aerospac, manu..."
4,musk criticized making unscientific contro...,"[musk, criticized, making, unscientific, contr...",[musk criticized making unscientific contr...,"[musk, critic, make, unscientif, controversi, ..."

### 7. Lemmatization (Reduction to Dictionary Form) 
 
**Instruction**: Use lemmatization to reduce inflected words to their base or dictionary form,  
the lemma. 
Method: It uses vocabulary and morphological analysis.

In [96]:
from nltk.stem import WordNetLemmatizer
# nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

df['lemmatization'] = df["Text"].apply(lambda x: [lemmatizer.lemmatize(word) for word in word_tokenize(x)])
df

,Text,word_tokens,sentence_tokens,word_stemming,lemmatization
0,,[],[],[],[]
1,elon reeve musk frs iln eelon born june 28 197...,"[elon, reeve, musk, frs, iln, eelon, born, jun...",[elon reeve musk frs iln eelon born june 28 19...,"[elon, reev, musk, frs, iln, eelon, born, june...","[elon, reeve, musk, fr, iln, eelon, born, june..."
2,musk born canadian mother white south afri...,"[musk, born, canadian, mother, white, south, a...",[musk born canadian mother white south afr...,"[musk, born, canadian, mother, white, south, a...","[musk, born, canadian, mother, white, south, a..."
3,in 2002 musk founded spacex aerospace manufac...,"[in, 2002, musk, founded, spacex, aerospace, m...",[in 2002 musk founded spacex aerospace manufa...,"[in, 2002, musk, found, spacex, aerospac, manu...","[in, 2002, musk, founded, spacex, aerospace, m..."
4,musk criticized making unscientific contro...,"[musk, criticized, making, unscientific, contr...",[musk criticized making unscientific contr...,"[musk, critic, make, unscientif, controversi, ...","[musk, criticized, making, unscientific, contr..."